  # A Ruby web service
  # - type: web
    name: sinatra
    env: ruby
    repo: https://github.com/travisl-code/ls-rb175-book-viewer
    buildCommand: bundle install
    startCommand: bundle exec ruby main.rb
